#!/usr/bin/env bash

# +--------+
# | System |
# +--------+

# alias shutdown='sudo shutdown now'

# +----+
# | ls |
# +----+

alias ls='ls --color=auto'
alias l='ls -lv'
alias ll='ls -lhv'
alias la='ls -lhAv'
# alias lls='ls -lahFtr'

# +-----+
# | Git |
# +-----+

alias gs='git status'
# alias gss='git status -s'
alias ga='git add'
alias gp='git push'
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
